import "./globals.css";
import { Inter } from "next/font/google";
import useTranslation from "next-translate/useTranslation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return ["en", "nl"].map((lang) => ({ lang }));
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { lang } = useTranslation();
  return (
    <html lang={lang}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
